# Generated by Django 4.1 on 2022-08-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='日付'),
        ),
    ]
