# Generated by Django 4.1 on 2022-08-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_weight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(verbose_name='体重'),
        ),
    ]
