# Generated by Django 4.1 on 2022-08-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
