# Generated by Django 4.1 on 2022-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_alter_weight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='body_fat',
            field=models.FloatField(default=0, verbose_name='体脂肪率'),
        ),
    ]
