# Generated by Django 4.1 on 2022-08-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_weight_body_fat'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='bmi',
            field=models.FloatField(default=0, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 11), verbose_name='日付'),
        ),
    ]
