# Generated by Django 4.1 on 2022-08-15 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_weight_bmi_alter_weight_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='身長')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男性'), (2, '女性')], null=True, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
        ),
        migrations.AlterField(
            model_name='weight',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 15), verbose_name='日付'),
        ),
    ]
